# typed: false
# frozen_string_literal: true

# This file was generated by the Kontext release workflow. DO NOT EDIT.
class Kontext < Formula
  desc "Identity, credentials, and governance for AI agents"
  homepage "https://kontext.security"
  version "0.8.0"
  license "MIT"

  depends_on "llama.cpp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kontext-security/kontext-cli/releases/download/v0.8.0/kontext_0.8.0_darwin_amd64.tar.gz"
      sha256 "2e91b886fa2a2d9a4dd466330b20dbbbdb6a74b1a25a8e33ca32026b1fa09ff8"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kontext-security/kontext-cli/releases/download/v0.8.0/kontext_0.8.0_darwin_arm64.tar.gz"
      sha256 "772cd2e69d239a3cc9cbe400b86778b636e5f129b3fe419ab2b2faa41b9a7743"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kontext-security/kontext-cli/releases/download/v0.8.0/kontext_0.8.0_linux_amd64.tar.gz"
      sha256 "3687b3824aa240b2324eaaf328590b0700257f6e58152f9e1ab6190e2e202c97"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kontext-security/kontext-cli/releases/download/v0.8.0/kontext_0.8.0_linux_arm64.tar.gz"
      sha256 "0b54dd25e77ec1d7b60021f8bc642d26687d1049523df47ed0b8982008f0a0b0"
    end
  end

  def install
    bin.install "kontext"
  end

  test do
    system bin/"kontext", "--version"
  end
end
